server:
 port: 8085
 servlet:
  context-path: /e-commerce
 error:
  path: /error

spring:

  datasource:
    url: <url>
    username: <username>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <github-id>
            clientSecret: <github-secret>
          google:
            clientId: <google-id>
            clientSecret: <google-secret>

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: <google-username>
    password: <google-password>
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true